format="""
$os\
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$docker_context\
$package\
$c\
$cmake\
$dotnet\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nodejs\
$perl\
$php\
$python\
$ruby\
$rust\
$zig\
$nix_shell\
$conda\
$meson\
$direnv\
$cmd_duration\
$time\
$line_break\
$jobs\
$container\
$netns\
$character"""

[os]
disabled = false
[os.symbols]
AlmaLinux = "\uf31d "
Alpine = "\uf300 "
Amazon = "\uf270 "
Android = "\uf17b "
Arch = "\uf303 "
Artix = "\uf31f "
CentOS = "\uf304 "
Debian = "\uf306 "
EndeavourOS = "\uf322 "
Fedora = "\uf30a "
FreeBSD = "\uf30c "
Garuda = "\uf337 "
Gentoo = "\uf30d "
Illumos = "\uf326 "
Kali = "\uf327 "
Linux = "\uf17c "
Macos = "\uf302 "
Manjaro = "\uf312 "
Mint = "\uf30e "
NixOS = "\uf313 "
Nobara = "\uf380 "
OpenBSD = "\uf328 "
openSUSE = "\uf314 "
Pop = "\uf32a "
Raspbian = "\uf315 "
Redhat = "\uf316 "
RedHatEnterprise = "\uf316 "
RockyLinux = "\uf32b "
Solus = "\uf32d "
SUSE = "\uf314 "
Ubuntu = "\uf31b "
Unknown = "❓ "
Void = "\uf32e "
Windows = "\uf17a "

[conda]
symbol = "\ue715 "

[directory]
read_only = "\ue672"

[docker_context]
symbol = "\ue7b0 "

[fill]
symbol = "\u2500"

[golang]
symbol = "\ue724 "

[lua]
symbol = "\ue826 "

[nix_shell]
symbol = "\ue843 "

[package]
symbol = "\uf487 "

[perl]
symbol = "\ue769 "

[php]
symbol = "\ue73d "

[python]
symbol = "\ue73c "

[shlvl]
disabled = false
symbol = "\uf07d"

[ruby]
symbol = "\ue739 "

[rust]
symbol = "\ue7a8 "

[time]
disabled = false
